import Navigation from "@/components/Navigation";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Aside from "@/components/Aside/Aside";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digitaly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navigation /> */}
        {/* <div className="flex flex-row">
          <Aside />
          <main className="flex flex-row min-h-screen flex-col items-center justify-between py-8  ml-64 ">
            {children}
          </main>
        </div>
        <Footer /> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
